<?php
return [
    'prog-sum-array' => [
        'materia' => 'Programación',
        'title' => 'Suma de elementos',
        'difficulty' => 'Fácil',
        'type' => 'code',
        'points' => 10,
        'description' => 'Crea una función que sume todos los elementos de un arreglo numérico.',
        'theory' => 'Arrays: estructuras que almacenan múltiples valores. Acceso por índice (comienza en 0).',
        'examples' => '[1,2,3] → 6 | [5,-2,7] → 10 | [0,0,0] → 0',
        'hint' => 'Usa un bucle for o el método reduce().',
        'starter' => "function solve(arr) {\n  // Suma todos los elementos\n  return 0;\n}",
        'tests' => [
            ['input' => [[1,2,3]], 'expected' => 6],
            ['input' => [[5,-2,7]], 'expected' => 10],
            ['input' => [[0,0,0]], 'expected' => 0],
            ['input' => [[100]], 'expected' => 100],
            ['input' => [[-5,-3,-2]], 'expected' => -10],
        ]
    ],
    'prog-palindromo' => [
        'materia' => 'Programación',
        'title' => 'Verificar palíndromo',
        'difficulty' => 'Medio',
        'type' => 'code',
        'points' => 15,
        'description' => 'Verifica si un texto es un palíndromo (se lee igual al derecho y al revés). Ignora espacios y mayúsculas.',
        'theory' => 'Palíndromos: textos que se leen igual en ambas direcciones después de normalizar.',
        'examples' => '"Anita lava la tina" → true | "Radar" → true | "Hola" → false',
        'hint' => 'Usa toLowerCase(), replace(/\\s+/g, "") y split("").reverse().join("")',
        'starter' => "function solve(text) {\n  // Normaliza y verifica si es palíndromo\n  return false;\n}",
        'tests' => [
            ['input' => ['Anita lava la tina'], 'expected' => true],
            ['input' => ['Radar'], 'expected' => true],
            ['input' => ['Hola mundo'], 'expected' => false],
            ['input' => ['A'], 'expected' => true],
            ['input' => ['Ab'], 'expected' => false],
        ]
    ],
    'prog-fizzbuzz' => [
        'materia' => 'Programación',
        'title' => 'FizzBuzz',
        'difficulty' => 'Fácil',
        'type' => 'code',
        'points' => 10,
        'description' => 'Múltiplo de 3→"Fizz", de 5→"Buzz", ambos→"FizzBuzz", ninguno→número como string',
        'theory' => 'Condicionales y operador módulo (%)',
        'examples' => 'solve(5) → ["1","2","Fizz","4","Buzz"]',
        'hint' => 'Usa un bucle y verifica: i%3===0, i%5===0',
        'starter' => "function solve(n) {\n  // Retorna array con FizzBuzz\n  return [];\n}",
        'tests' => [
            ['input' => [5], 'expected' => ['1','2','Fizz','4','Buzz']],
            ['input' => [15], 'expected' => ['1','2','Fizz','4','Buzz','Fizz','7','8','Fizz','Buzz','11','Fizz','13','14','FizzBuzz']],
        ]
    ],
    'prog-fibonacci' => [
        'materia' => 'Programación',
        'title' => 'Fibonacci',
        'difficulty' => 'Medio',
        'type' => 'code',
        'points' => 15,
        'description' => 'Genera los primeros n números de Fibonacci (comenzando con 1,1)',
        'theory' => 'Sucesión: 1,1,2,3,5,8... donde cada número es la suma de los dos anteriores.',
        'examples' => 'solve(6) → [1,1,2,3,5,8]',
        'hint' => 'Usa un bucle con dos variables para los últimos dos números',
        'starter' => "function solve(n) {\n  // Retorna array con n números de Fibonacci\n  return [];\n}",
        'tests' => [
            ['input' => [6], 'expected' => [1,1,2,3,5,8]],
            ['input' => [1], 'expected' => [1]],
            ['input' => [2], 'expected' => [1,1]],
            ['input' => [10], 'expected' => [1,1,2,3,5,8,13,21,34,55]],
        ]
    ],
    'prog-closure' => [
        'materia' => 'Programación',
        'title' => 'Closures',
        'difficulty' => 'Difícil',
        'type' => 'code',
        'points' => 20,
        'description' => 'Crea una función que retorna otra función multiplicadora',
        'theory' => 'Closures: función que recuerda el contexto donde fue creada',
        'examples' => 'solve(2)(5) → 10',
        'hint' => 'Función externa recibe factor, retorna función interna que multiplica',
        'starter' => "function solve(factor) {\n  // Retorna función multiplicadora\n  return function(x) { return 0; };\n}",
        'tests' => [
            ['input' => [2, 5], 'expected' => 10],
            ['input' => [3, 4], 'expected' => 12],
            ['input' => [5, 1], 'expected' => 5],
        ]
    ],
    'mat-derivada' => [
        'materia' => 'Pensamiento Matemático III',
        'title' => 'Derivada básica',
        'difficulty' => 'Medio',
        'type' => 'math',
        'points' => 12,
        'description' => 'Calcula la derivada de f(x)=ax²+bx+c en x=x₀',
        'theory' => 'La derivada mide la tasa de cambio instantánea. Regla: $$\\frac{d}{dx}[x^n] = nx^{n-1}$$',
        'examples' => 'f\'(x) = 2ax + b → f\'(x₀) = 2ax₀ + b',
        'hint' => 'Deriva cada término: ax²→2ax, bx→b, c→0',
        'input_type' => 'formula',
        'params' => [
            ['name' => 'a', 'label' => 'Coeficiente \(a\)', 'type' => 'slider', 'min' => -5, 'max' => 5, 'value' => 3],
            ['name' => 'b', 'label' => 'Coeficiente \(b\)', 'type' => 'slider', 'min' => -10, 'max' => 10, 'value' => 2],
            ['name' => 'x', 'label' => 'Evaluar en \(x_0\)', 'type' => 'slider', 'min' => -5, 'max' => 5, 'value' => 2],
        ],
        'calculate' => 'a * 2 * x + b',
        'answer' => 14,
        'formula' => 'f\'(x_0) = 2ax_0 + b',
        'visualize' => false,
    ],
    'mat-integral' => [
        'materia' => 'Pensamiento Matemático III',
        'title' => 'Integral definida',
        'difficulty' => 'Medio',
        'type' => 'math',
        'points' => 16,
        'description' => 'Calcula la integral definida \(\\int_a^b (mx + n) dx\)',
        'theory' => 'Integral definida: $$\\int_a^b f(x)dx = F(b) - F(a)$$ donde F es la antiderivada.',
        'examples' => '\\(\\int_0^2 (2x + 1)dx = [x^2 + x]_0^2 = 6\\)',
        'hint' => 'Antiderivada de mx es mx²/2, de n es nx',
        'input_type' => 'number',
        'params' => [
            ['name' => 'm', 'label' => 'Pendiente \(m\)', 'type' => 'slider', 'min' => 1, 'max' => 5, 'value' => 2],
            ['name' => 'n', 'label' => 'Intersección \(n\)', 'type' => 'slider', 'min' => 0, 'max' => 5, 'value' => 1],
            ['name' => 'a', 'label' => 'Límite inferior \(a\)', 'type' => 'slider', 'min' => 0, 'max' => 3, 'value' => 0],
            ['name' => 'b', 'label' => 'Límite superior \(b\)', 'type' => 'slider', 'min' => 1, 'max' => 5, 'value' => 2],
        ],
        'calculate' => '(m*b*b/2 + n*b) - (m*a*a/2 + n*a)',
        'answer' => 6,
        'visualize' => false,
    ],
    'mat-funcion' => [
        'materia' => 'Pensamiento Matemático III',
        'title' => 'Evaluar función cuadrática',
        'difficulty' => 'Fácil',
        'type' => 'math',
        'points' => 10,
        'description' => 'Evalúa la función cuadrática \(f(x) = ax^2 + bx + c\)',
        'theory' => 'Función cuadrática: $$f(x) = ax^2 + bx + c$$ donde a≠0',
        'examples' => 'f(2) con a=1,b=-3,c=2 → 1(4) -3(2) + 2 = 0',
        'hint' => 'Sustituye x en la fórmula',
        'input_type' => 'number',
        'params' => [
            ['name' => 'a', 'label' => 'a =', 'type' => 'slider', 'min' => -5, 'max' => 5, 'value' => 1],
            ['name' => 'b', 'label' => 'b =', 'type' => 'slider', 'min' => -10, 'max' => 10, 'value' => -3],
            ['name' => 'c', 'label' => 'c =', 'type' => 'slider', 'min' => -10, 'max' => 10, 'value' => 2],
            ['name' => 'x', 'label' => 'x =', 'type' => 'slider', 'min' => -5, 'max' => 5, 'value' => 2],
        ],
        'calculate' => 'a*x*x + b*x + c',
        'answer' => 0,
        'visualize' => true,
    ],
    'fis-velocidad' => [
        'materia' => 'Física I',
        'title' => 'Velocidad promedio',
        'difficulty' => 'Fácil',
        'type' => 'physics',
        'points' => 10,
        'description' => 'Calcula la velocidad promedio: $$v = \\frac{d}{t}$$',
        'theory' => 'Velocidad = distancia / tiempo. Unidad: km/h o m/s',
        'examples' => '120km en 2h → 60 km/h',
        'hint' => 'Simple: velocidad = distancia ÷ tiempo',
        'input_type' => 'number',
        'params' => [
            ['name' => 'distancia', 'label' => 'Distancia (km)', 'type' => 'slider', 'min' => 10, 'max' => 200, 'value' => 120],
            ['name' => 'tiempo', 'label' => 'Tiempo (horas)', 'type' => 'slider', 'min' => 0.5, 'max' => 5, 'step' => 0.5, 'value' => 2],
        ],
        'calculate' => 'distancia / tiempo',
        'answer' => 60,
    ],
    'fis-energia' => [
        'materia' => 'Física I',
        'title' => 'Energía cinética',
        'difficulty' => 'Medio',
        'type' => 'physics',
        'points' => 13,
        'description' => 'Calcula la energía cinética: $$E_c = \\frac{1}{2}mv^2$$',
        'theory' => 'Energía cinética: Ec = ½mv². Unidad: Joules (J)',
        'examples' => 'm=5kg, v=10m/s → Ec = 250 J',
        'hint' => 'No olvides el ½ y que v está al cuadrado',
        'input_type' => 'number',
        'params' => [
            ['name' => 'masa', 'label' => 'Masa (kg)', 'type' => 'slider', 'min' => 1, 'max' => 20, 'value' => 5],
            ['name' => 'velocidad', 'label' => 'Velocidad (m/s)', 'type' => 'slider', 'min' => 1, 'max' => 30, 'value' => 10],
        ],
        'calculate' => '0.5 * masa * velocidad * velocidad',
        'answer' => 250,
    ],
    'fis-fuerza' => [
        'materia' => 'Física I',
        'title' => 'Segunda ley de Newton',
        'difficulty' => 'Medio',
        'type' => 'physics',
        'points' => 12,
        'description' => 'Calcula la fuerza: $$F = ma$$',
        'theory' => 'Segunda Ley de Newton: F = m × a. Fuerza en Newtons (N)',
        'examples' => 'm=10kg, a=5m/s² → F = 50 N',
        'hint' => 'Multiplica masa por aceleración',
        'input_type' => 'number',
        'params' => [
            ['name' => 'masa', 'label' => 'Masa (kg)', 'type' => 'slider', 'min' => 1, 'max' => 50, 'value' => 10],
            ['name' => 'aceleracion', 'label' => 'Aceleración (m/s²)', 'type' => 'slider', 'min' => 1, 'max' => 20, 'value' => 5],
        ],
        'calculate' => 'masa * aceleracion',
        'answer' => 50,
    ],
    'quim-mol' => [
        'materia' => 'Química I',
        'title' => 'Cálculo de moles',
        'difficulty' => 'Fácil',
        'type' => 'chemistry',
        'points' => 10,
        'description' => 'Calcula moles: $$n = \\frac{m}{M}$$',
        'theory' => 'Moles = masa / masa molar. 1 mol = 6.022×10²³ partículas',
        'examples' => '18g de H₂O (M=18) → 1 mol',
        'hint' => 'Fórmula: moles = masa ÷ masa molar',
        'input_type' => 'number',
        'params' => [
            ['name' => 'masa', 'label' => 'Masa (g)', 'type' => 'slider', 'min' => 1, 'max' => 100, 'value' => 18],
            ['name' => 'molar', 'label' => 'Masa molar (g/mol)', 'type' => 'slider', 'min' => 1, 'max' => 200, 'value' => 18],
        ],
        'calculate' => 'masa / molar',
        'answer' => 1,
    ],
    'quim-ph' => [
        'materia' => 'Química I',
        'title' => 'pH de solución',
        'difficulty' => 'Medio',
        'type' => 'chemistry',
        'points' => 12,
        'description' => 'Calcula el pH: $$pH = -\\log[H^+]$$',
        'theory' => 'pH = -log₁₀[H⁺]. Escala: <7 ácido, =7 neutro, >7 básico',
        'examples' => '[H⁺]=10⁻³ → pH=3',
        'hint' => 'log₁₀(10ⁿ) = n',
        'input_type' => 'number',
        'params' => [
            ['name' => 'exponente', 'label' => 'Exponente de [H⁺] = 10^x', 'type' => 'slider', 'min' => -14, 'max' => 0, 'value' => -3],
        ],
        'calculate' => '-exponente',
        'answer' => 3,
    ],
    'quim-masa' => [
        'materia' => 'Química I',
        'title' => 'Masa molecular',
        'difficulty' => 'Fácil',
        'type' => 'chemistry',
        'points' => 10,
        'description' => 'Calcula la masa molecular: $$M = \\sum m_i n_i$$',
        'theory' => 'Masa molecular = Σ masas atómicas de los elementos',
        'examples' => 'H₂O: 2(1) + 16 = 18 g/mol',
        'hint' => 'Cuenta cuántos átomos de cada elemento',
        'input_type' => 'number',
        'params' => [
            ['name' => 'H', 'label' => 'Átomos de H (masa=1)', 'type' => 'slider', 'min' => 0, 'max' => 10, 'value' => 2],
            ['name' => 'O', 'label' => 'Átomos de O (masa=16)', 'type' => 'slider', 'min' => 0, 'max' => 5, 'value' => 1],
        ],
        'calculate' => 'H * 1 + O * 16',
        'answer' => 18,
    ],
    'eco-cadena' => [
        'materia' => 'Ecosistemas',
        'title' => 'Eficiencia energética',
        'difficulty' => 'Fácil',
        'type' => 'simulation',
        'points' => 10,
        'description' => '¿Cuánta energía se transfiere entre niveles tróficos?',
        'theory' => '~10% se transfiere, 90% se pierde como calor. Segunda Ley de Termodinámica.',
        'examples' => '1000kcal → 100kcal → 10kcal',
        'hint' => 'Regla del 10%',
        'input_type' => 'number',
        'params' => [
            ['name' => 'energia', 'label' => 'Energía nivel anterior (kcal)', 'type' => 'slider', 'min' => 100, 'max' => 10000, 'value' => 1000],
        ],
        'calculate' => 'energia * 0.1',
        'answer' => 100,
        'visualize' => true,
    ],
    'eco-fotosintesis' => [
        'materia' => 'Ecosistemas',
        'title' => 'Productores primarios',
        'difficulty' => 'Fácil',
        'type' => 'simulation',
        'points' => 10,
        'description' => 'Simula la producción de glucosa por fotosíntesis',
        'theory' => '6CO₂ + 6H₂O + luz → C₆H₁₂O₆ + 6O₂',
        'examples' => 'Luz → Glucosa + Oxígeno',
        'hint' => 'Las plantas son autótrofos',
        'input_type' => 'number',
        'params' => [
            ['name' => 'luz', 'label' => 'Intensidad de luz (%)', 'type' => 'slider', 'min' => 0, 'max' => 100, 'value' => 50],
        ],
        'calculate' => 'luz * 0.01 * 6',
    ],
    'eco-poblacion' => [
        'materia' => 'Ecosistemas',
        'title' => 'Crecimiento poblacional',
        'difficulty' => 'Medio',
        'type' => 'simulation',
        'points' => 12,
        'description' => 'Simula el crecimiento exponencial: $$P(t) = P_0 e^{rt}$$',
        'theory' => 'Crecimiento exponencial: P(t) = P₀ × e^(rt)',
        'examples' => '100 conejos, r=0.5 → ~270 en 2 años',
        'hint' => 'Población crece exponencialmente',
        'input_type' => 'number',
        'params' => [
            ['name' => 'P0', 'label' => 'Población inicial', 'type' => 'slider', 'min' => 10, 'max' => 500, 'value' => 100],
            ['name' => 'r', 'label' => 'Tasa de crecimiento r', 'type' => 'slider', 'min' => 0.1, 'max' => 1.0, 'step' => 0.1, 'value' => 0.5],
            ['name' => 't', 'label' => 'Tiempo (años)', 'type' => 'slider', 'min' => 1, 'max' => 5, 'value' => 2],
        ],
        'calculate' => 'P0 * Math.exp(r * t)',
        'answer' => 271,
    ],
];