<?php
/**
 * Lesson data loader — auto-generated by scripts/split_lessons.php
 */
$lecciones = [];
$lecciones = array_merge($lecciones, require __DIR__ . '/lessons/pensamiento_matemtico_iii.php');
$lecciones = array_merge($lecciones, require __DIR__ . '/lessons/ecosistemas.php');
$lecciones = array_merge($lecciones, require __DIR__ . '/lessons/qumica_i.php');
$lecciones = array_merge($lecciones, require __DIR__ . '/lessons/fsica_i.php');
$lecciones = array_merge($lecciones, require __DIR__ . '/lessons/ciencias_sociales.php');
$lecciones = array_merge($lecciones, require __DIR__ . '/lessons/historia_de_mxico.php');
$lecciones = array_merge($lecciones, require __DIR__ . '/lessons/programacin.php');
$lecciones = array_merge($lecciones, require __DIR__ . '/lessons/temas_selectos_de_matemticas_i_y_ii.php');
$lecciones = array_merge($lecciones, require __DIR__ . '/lessons/ingls.php');
