<?php
/**
 * Splits src/Content/content.php into per-subject files.
 * Run: php scripts/split_lessons.php
 */

require_once __DIR__ . '/../src/Content/content.php';

$outDir = __DIR__ . '/../src/Content/lessons';
if (!is_dir($outDir)) {
    mkdir($outDir, 0755, true);
}

// Group by subject
$groups = [];
foreach ($lecciones as $l) {
    $m = $l['materia'] ?? 'unknown';
    $groups[$m][] = $l;
}

// Generate a filesystem-safe name from subject name
function subjectSlug($name) {
    $slug = mb_strtolower($name, 'UTF-8');
    $slug = str_replace([' ', '-'], '_', $slug);
    $slug = preg_replace('/[^a-z0-9_\x{4e00}-\x{9fff}]/u', '', $slug);
    $slug = preg_replace('/_+/', '_', $slug);
    $slug = trim($slug, '_');
    return $slug ?: 'unknown';
}

$loaderLines = "<?php\n/**\n * Lesson data loader — auto-generated by scripts/split_lessons.php\n */\n\$lecciones = [];\n";

foreach ($groups as $subject => $lessons) {
    $slug = subjectSlug($subject);
    $file = $outDir . '/' . $slug . '.php';

    // Build the array with var_export, then wrap with return
    $export = var_export($lessons, true);
    $content = "<?php\n/**\n * Materia: $subject\n * Lecciones: " . count($lessons) . "\n */\nreturn $export;\n";

    file_put_contents($file, $content);
    echo "Wrote $file (" . count($lessons) . " lecciones)\n";

    $loaderLines .= "\$lecciones = array_merge(\$lecciones, require __DIR__ . '/lessons/$slug.php');\n";
}

// Write loader lines to stdout
echo "\n--- Add this to the top of src/Config/compileLecciones() include ---\n";
echo $loaderLines;

// Also write a new content.php
$newContent = $loaderLines;
file_put_contents(__DIR__ . '/../src/Content/content.php', $newContent);
echo "\nReplaced src/Content/content.php with loader\n";

// Clear compiled cache
$cacheFile = __DIR__ . '/../cache/lecciones_compiled.php';
if (is_file($cacheFile)) {
    unlink($cacheFile);
    echo "Deleted cache: $cacheFile\n";
}

echo "\nDone.\n";
